"""add tags param into cocktail model

Revision ID: 39c413e0e5b6
Revises: 
Create Date: 2023-04-02 22:03:29.055218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c413e0e5b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cocktails', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cocktails', 'tags')
    # ### end Alembic commands ###
