"""reformat tags

Revision ID: 3de1d10170da
Revises: 5548f0e9a594
Create Date: 2023-04-16 22:37:24.923222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3de1d10170da"
down_revision = "5548f0e9a594"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("category", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tags", "category")
    # ### end Alembic commands ###
