"""reformat tags

Revision ID: 5548f0e9a594
Revises: f1d4c3bbf500
Create Date: 2023-04-16 22:34:27.125106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5548f0e9a594"
down_revision = "f1d4c3bbf500"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
