"""add administration rights to user class

Revision ID: c3aa04467d50
Revises: cfbd5ae42a28
Create Date: 2023-04-09 23:20:56.350516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3aa04467d50'
down_revision = 'cfbd5ae42a28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
