"""add image to cocktail class

Revision ID: cfbd5ae42a28
Revises: 39c413e0e5b6
Create Date: 2023-04-09 20:15:05.316918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cfbd5ae42a28"
down_revision = "39c413e0e5b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cocktails", sa.Column("photo", sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cocktails", "photo")
    # ### end Alembic commands ###
